[package]
name = "hypersonic"
version = "0.1.0"
edition = "2021"

[dependencies]
futures = "0.3"
symphonia = { features = ["aac", "mp3", "isomp4", "alac"], version = "0.5" }
tracing = "0.1"
tracing-subscriber = "0.3"
tokio = { features = ["macros", "rt-multi-thread", "sync", "signal"], version = "1" }
twilight-gateway = "0.15"
twilight-http = "0.15"
twilight-model = "0.15"
dotenvy = "0.15"
serde = { version = "1", features = ["derive"] }
serde_json = "1"

[dependencies.songbird]
default-features = false
git = "https://github.com/serenity-rs/songbird"
branch = "next"
features = ["driver", "gateway", "twilight", "rustls"]
